backend:
  name: github
  repo: arecatour/areca-treks-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "website"
    label: "Website Content"
    files:
      - file: "index.html"
        label: "Edit Full Website"
        name: "homepage"
        fields:
          - { label: "Website Code", name: "body", widget: "code", default_language: "html" }
